version: '3'

services:
  website:
    command: "gunicorn -w 3 --bind 0.0.0.0:5000 wsgi:app"
    ports:
      - 5000:5000
    environment:
      - FLASK_DEBUG=false

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/sites-enabled.conf:/etc/nginx/conf.d/sites-enabled.conf
      - ./moldsamerica/static:/static
    expose:
      - 8000
    ports:
      - 80:8000
    depends_on:
      - website

